spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: mongodb+srv://Przemo:nfBW1z647cUioCNV@cluster0.a2wxm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: chwalik_admin

application:
  discord:
    botToken: ${BOT_TOKEN}
  tweetpik:
    apiKey: ${TWEETPIK_APIKEY_TOKEN}
  twitch:
    clientSecret: lyr1qt6sg1g7k2suuia4exbny4apc1 #${TWITCH_CLIENTSECRET_TOKEN}
    clientId: kimv4iz3l99i23wj531dgwvqq68jcj #${TWITCH_CLIENTID_TOKEN}
  twitter:
    apiKey: ${TWITTER_APIKEY_TOKEN}