spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: mongodb+srv://Przemo:nfBW1z647cUioCNV@cluster0.a2wxm.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: chwalik_admin

application:
  discord:
    botToken: ${BOT_DISCORD_TOKEN}
  tweetpik:
    apiKey: ${BOT_TWEETPIK_KEY}
  twitch:
    clientSecret: ${BOT_TWITCH_CLIENT_SECRET}
    clientId: ${BOT_TWITCH_CLIENT_ID}
  twitter:
    apiKey: ${BOT_TWITTER_KEY}