spring:
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: ${BOT_MONGO_URI}
      database: chwalik_admin

application:
  discord:
    botToken: ${BOT_DISCORD_TOKEN}
  tweetpik:
    apiKey: ${BOT_TWEETPIK_KEY}
  twitch:
    clientSecret: ${BOT_TWITCH_CLIENT_SECRET}
    clientId: ${BOT_TWITCH_CLIENT_ID}
  twitter:
    apiKey: ${BOT_TWITTER_KEY}